import React, { useState } from 'react'
import './testimonials.css'
import AVTR1 from '../../assets/avatar1.jpg'
import AVTR2 from '../../assets/avatar2.jpg'
import AVTR3 from '../../assets/avatar3.png'
import AVTR4 from '../../assets/avatar4.jpg'
import StyledTestimonialCard from './StyledTestimonialCard'

// import Swiper core and required modules
import { Pagination } from 'swiper';

import { Swiper, SwiperSlide } from 'swiper/react';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/pagination';

const data = [
  {
    avatar: AVTR1,
    name: 'Hazel Stephenson',
    review: '"Travis is an amazing software developer and a one of a kind creative mind. His work spanned in tech, design, quality assurance testing, and most importantly projects in the private sector." ',
    rating: 5
  },
  {
    avatar: AVTR2,
    name: 'Jackson Party',
    review: '"Travis managed our software project so well it was like it was on autopilot but the quality was amazing. He had a knack for finding what he needed in the client documents and finding how he could build on them and improve them. He did a lot of code re-fractoring to create the native mobile phone!"',
    rating: 5
  },
  {
    avatar: AVTR3,
    name: 'Ciri from Ciri and Friends',
    review: '"Travis created the Ciri and Friends app in a cave with his bare hands, with a box of scraps. He even arranged the credits on his own, explaining, "Not knowing how to make videos or how to write a website, I just kind of did it all by myself." After some convincing from Travis, and with the help of amazing voices and a voice talent agency, Nintendo allowed him to create a video of the project on YouTube. It was viewed hundreds of thousands of times, and even landed Travis a lucrative camera operating deal."',
    rating: 5
  },
  {
    avatar: AVTR4,
    name: 'Claire Curtis',
    review: '"I was paid $20 for this review of Travis and his software development skills. He seems like a great guy. Blogging (and doing articles for magazines) was my main source of income for the past 6 years. I cannot afford to pay all my bills from my writing, so I am looking for another way to make money. Hence being paid for this review."',
    rating: 5
  },
]

const Testimonials = () => {
  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <section id='testimonials'>
      <h5 style={{ 
        color: '#E6E6FA',
        fontSize: '1.2rem',
        fontWeight: '400',
        fontFamily: "'Inter', 'Segoe UI', 'Roboto', sans-serif",
        letterSpacing: '0.05em',
        textTransform: 'uppercase'
      }}>Review from clients as generated by AI</h5>
      <h2 style={{ 
        color: 'white',
        fontSize: '2.5rem',
        fontWeight: '700',
        fontFamily: "'Inter', 'Segoe UI', 'Roboto', sans-serif",
        letterSpacing: '0.05em',
        textTransform: 'uppercase',
        textShadow: '0 0 20px rgba(255,255,255,0.3)'
      }}>Testimonials</h2>

      <div style={{ display: 'flex', justifyContent: 'center', width: '100%' }}>
        <Swiper className="container testimonials__container" 
        // install Swiper modules
        modules={[Pagination]} 
        spaceBetween={40}
        slidesPerView={1.2}
        centeredSlides={true}
        loop={true}
        initialSlide={0}
        pagination={{ clickable: true }}
        onSlideChange={(swiper) => setActiveIndex(swiper.realIndex)}>
          {
            data.map(({avatar, name, review, rating}, index) => {
              return (
                <SwiperSlide key={index} className="testimonial">
                  <StyledTestimonialCard 
                    avatar={avatar}
                    name={name}
                    review={review}
                    rating={rating}
                    isActive={activeIndex === index}
                  />
                </SwiperSlide>
              )
            })
          }
        </Swiper>
      </div>
    </section>
  )
}

export default Testimonials